{% set name = "ooipy" %}
{% set version = "1.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b51634ebeafc9e98ce8a55f7af0a81bae0baede16f2ee44c2ac5daad8e5d73e6

build:
  number: 1
  noarch: python
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}    # [unix]
    - set SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}    # [win]
    - {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=45
    - setuptools_scm >=3.4
    - toml
  run:
    - aiohttp
    - fsspec
    - obspy
    - python >={{ python_min }}
    - pandas

test:
  imports:
    - ooipy
    - ooipy.hydrophone
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ooipy/ooipy
  summary: A python toolbox for acquiring and analyzing Ocean Obvservatories Initiative (OOI) Data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lsetiawan
    - John-Ragland
    - FelixSchwock
